version: '3.8'

services:
  db:
    image: postgres:17.5-alpine
    restart: always
    environment:
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      POSTGRES_DB: ${APP_DB_NAME}
    ports:
      - ${APP_DB_PORT}:${APP_DB_PORT}
  app:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/app
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - 9000
  web:
    image: nginx:1.27.5-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
      #- ToDo: нужно логи выводить прям в проект
    ports:
      - 80:80
    restart: always
    depends_on:
      - app
      - db